/**
 * Static AI product catalog — used as immediate initial state for the AI Tools page.
 * If Firestore is available the live data will replace this; if not, this always renders.
 *
 * IDs match Firestore document IDs (slug format).
 * Affiliate URLs are embedded directly so referral links work without a server redirect.
 */
import type { AIProduct } from '../types/aiProducts';
import { buildAffiliateUrl } from './affiliateCodes';

// Omit Firestore-specific timestamp fields for static data
type StaticProduct = Omit<AIProduct, 'createdAt' | 'updatedAt'>;

const STATIC_PRODUCTS: StaticProduct[] = [
  // ─── LLM APIs ─────────────────────────────────────────────────────────────
  {
    id: 'anthropic-claude',
    name: 'Anthropic Claude',
    tagline: 'The AI assistant that is safe, beneficial, and honest',
    description:
      'Claude is the frontier AI model trusted by enterprises for reasoning, coding, summarization, and long-context analysis. NDN Analytics is built on Claude — we integrate it into clients\' workflows every day.',
    logoUrl: 'https://www.anthropic.com/favicon.ico',
    websiteUrl: 'https://www.anthropic.com',
    affiliateUrl: buildAffiliateUrl('https://www.anthropic.com/claude', 'anthropic', 'aitools'),
    affiliateProgramUrl: 'https://www.anthropic.com/partner',
    affiliateProgram: 'anthropic',
    commissionRate: 'Referral program',
    cookieDuration: 30,
    ndnServiceTieIn:
      'NDN Analytics uses Claude as the AI backbone for ARIA, our enterprise chatbot. Let us integrate Claude into your workflows.',
    category: 'llm_api',
    tags: ['llm', 'api', 'enterprise', 'reasoning', 'coding', 'safety'],
    pricing: 'paid',
    featured: true,
    sortOrder: 1,
    badge: 'Powers NDN',
    clickCount: 0,
    isActive: true,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    tagline: "GPT-4o, o1, and the world's most capable AI models",
    description:
      'OpenAI provides the GPT-4o and o1 model families through a developer-friendly API. Industry-leading multimodal capabilities for text, images, audio, and code generation at enterprise scale.',
    logoUrl: 'https://openai.com/favicon.ico',
    websiteUrl: 'https://openai.com',
    affiliateUrl: buildAffiliateUrl('https://platform.openai.com/signup', 'openai', 'aitools'),
    affiliateProgram: 'openai',
    commissionRate: 'Affiliate program',
    cookieDuration: 30,
    ndnServiceTieIn:
      'NDN Analytics benchmarks GPT-4o versus Claude for your specific use case and integrates the winning model into your stack.',
    category: 'llm_api',
    tags: ['llm', 'api', 'gpt', 'multimodal', 'enterprise'],
    pricing: 'paid',
    featured: true,
    sortOrder: 2,
    badge: 'Industry Leader',
    clickCount: 0,
    isActive: true,
  },

  // ─── Developer Tools ──────────────────────────────────────────────────────
  {
    id: 'cursor',
    name: 'Cursor',
    tagline: 'The AI-first code editor built on VS Code',
    description:
      'Cursor is an AI-native IDE that understands your entire codebase. Multi-line edits, codebase chat, and AI terminal commands make it the fastest way to ship software. NDN Analytics uses Cursor internally.',
    logoUrl: 'https://cursor.sh/favicon.ico',
    websiteUrl: 'https://cursor.sh',
    affiliateUrl: buildAffiliateUrl('https://cursor.sh', 'cursor', 'aitools'),
    affiliateProgram: 'direct',
    ndnServiceTieIn:
      'NDN Analytics trains engineering teams on AI-assisted development using Cursor workflows.',
    category: 'dev_tools',
    tags: ['ide', 'coding', 'ai-assistant', 'developer', 'productivity'],
    pricing: 'freemium',
    featured: true,
    sortOrder: 10,
    badge: 'Team Favourite',
    clickCount: 0,
    isActive: true,
  },
  {
    id: 'retool',
    name: 'Retool',
    tagline: 'Build internal tools remarkably fast',
    description:
      'Retool lets you build internal dashboards, admin panels, and data apps on top of any database or API — without building a frontend from scratch. AI-accelerated with Retool AI for natural-language app generation.',
    logoUrl: 'https://retool.com/favicon.ico',
    websiteUrl: 'https://retool.com',
    affiliateUrl: buildAffiliateUrl('https://retool.com', 'retool', 'aitools'),
    affiliateProgramUrl: 'https://retool.com/partners',
    affiliateProgram: 'retool',
    commissionRate: '20% first year',
    cookieDuration: 90,
    ndnServiceTieIn:
      'NDN Analytics builds and deploys production Retool apps for enterprise clients — from supply chain dashboards to DeFi portfolio trackers.',
    category: 'dev_tools',
    tags: ['low-code', 'internal-tools', 'dashboard', 'admin-panel'],
    pricing: 'freemium',
    featured: true,
    sortOrder: 11,
    badge: 'Partner',
    clickCount: 0,
    isActive: true,
  },
  {
    id: 'linear',
    name: 'Linear',
    tagline: 'The issue tracker built for modern software teams',
    description:
      'Linear brings speed and clarity to software projects with AI-assisted issue creation, automatic triage, and intelligent project planning that keeps teams focused on shipping.',
    logoUrl: 'https://linear.app/favicon.ico',
    websiteUrl: 'https://linear.app',
    affiliateUrl: buildAffiliateUrl('https://linear.app', 'linear', 'aitools'),
    affiliateProgram: 'linear',
    commissionRate: '20%',
    cookieDuration: 60,
    ndnServiceTieIn:
      'NDN Analytics integrates Linear project data into custom analytics dashboards so leadership always has real-time visibility.',
    category: 'dev_tools',
    tags: ['project-management', 'issue-tracker', 'devops', 'planning'],
    pricing: 'freemium',
    featured: false,
    sortOrder: 12,
    clickCount: 0,
    isActive: true,
  },

  // ─── Productivity ─────────────────────────────────────────────────────────
  {
    id: 'notion',
    name: 'Notion',
    tagline: 'The connected workspace with AI built in',
    description:
      'Notion combines docs, wikis, databases, and project management into one collaborative workspace. Notion AI drafts, summarizes, and answers questions across all your team\'s knowledge.',
    logoUrl: 'https://www.notion.so/images/favicon.ico',
    websiteUrl: 'https://www.notion.com',
    affiliateUrl: buildAffiliateUrl('https://www.notion.com', 'notion', 'aitools'),
    affiliateProgramUrl: 'https://www.notion.com/affiliates',
    affiliateProgram: 'notion',
    commissionRate: '50% first year',
    cookieDuration: 90,
    ndnServiceTieIn:
      "NDN Analytics builds your team's Notion operating system — SOPs, project hubs, client databases, and AI-assisted knowledge bases.",
    category: 'productivity',
    tags: ['docs', 'wiki', 'collaboration', 'ai-writing', 'project-management'],
    pricing: 'freemium',
    featured: true,
    sortOrder: 20,
    badge: '50% Commission',
    clickCount: 0,
    isActive: true,
  },
  {
    id: 'jasper-ai',
    name: 'Jasper AI',
    tagline: 'AI copilot for enterprise marketing teams',
    description:
      'Generate marketing copy, blog posts, social media content, and ads at scale. Jasper is used by 100,000+ teams worldwide and integrates with your entire marketing stack.',
    logoUrl: 'https://www.jasper.ai/favicon.ico',
    websiteUrl: 'https://www.jasper.ai',
    affiliateUrl: buildAffiliateUrl('https://www.jasper.ai', 'partnerstack', 'aitools'),
    affiliateProgramUrl: 'https://www.jasper.ai/partners',
    affiliateProgram: 'partnerstack',
    commissionRate: '30% recurring',
    cookieDuration: 30,
    ndnServiceTieIn:
      'NDN Analytics integrates Jasper into your content pipeline for automated blog generation and multi-channel marketing.',
    category: 'productivity',
    tags: ['ai', 'writing', 'marketing', 'content', 'copywriting'],
    pricing: 'paid',
    featured: true,
    sortOrder: 21,
    badge: '30% Recurring',
    clickCount: 0,
    isActive: true,
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    tagline: 'AI-powered copywriting at scale',
    description:
      'Create marketing copy, product descriptions, and sales content in seconds. Trusted by 10M+ users, Copy.ai automates GTM workflows and entire content operations.',
    logoUrl: 'https://www.copy.ai/favicon.ico',
    websiteUrl: 'https://www.copy.ai',
    affiliateUrl: buildAffiliateUrl('https://www.copy.ai', 'partnerstack', 'aitools'),
    affiliateProgramUrl: 'https://www.copy.ai/partners',
    affiliateProgram: 'partnerstack',
    commissionRate: '45% first year',
    cookieDuration: 60,
    ndnServiceTieIn:
      'Our team embeds Copy.ai workflows into your marketing automation stack for fully autonomous content production.',
    category: 'productivity',
    tags: ['ai', 'writing', 'copywriting', 'marketing', 'gtm'],
    pricing: 'freemium',
    featured: true,
    sortOrder: 22,
    badge: '45% Commission',
    clickCount: 0,
    isActive: true,
  },
  {
    id: 'otter-ai',
    name: 'Otter.ai',
    tagline: 'AI meeting assistant and transcription',
    description:
      'Automated meeting notes, real-time transcription, and AI summaries. Integrates with Zoom, Microsoft Teams, and Google Meet to capture every decision and action item.',
    logoUrl: 'https://otter.ai/favicon.ico',
    websiteUrl: 'https://otter.ai',
    affiliateUrl: buildAffiliateUrl('https://otter.ai', 'impact', 'aitools'),
    affiliateProgramUrl: 'https://otter.ai/affiliates',
    affiliateProgram: 'impact',
    commissionRate: '20%',
    cookieDuration: 30,
    ndnServiceTieIn:
      'NDN Interpreter handles real-time ASL translation with similar edge-AI technology — built for inclusivity at enterprise scale.',
    category: 'productivity',
    tags: ['ai', 'transcription', 'meetings', 'notes', 'automation'],
    pricing: 'freemium',
    featured: false,
    sortOrder: 23,
    clickCount: 0,
    isActive: true,
  },

  // ─── Design & Creative ────────────────────────────────────────────────────
  {
    id: 'synthesia',
    name: 'Synthesia',
    tagline: 'AI video generation platform',
    description:
      'Create professional AI avatar videos from text in minutes. No cameras, studios, or actors required. Used by 50,000+ teams for training, marketing, and communications at scale.',
    logoUrl: 'https://www.synthesia.io/favicon.ico',
    websiteUrl: 'https://www.synthesia.io',
    affiliateUrl: buildAffiliateUrl('https://www.synthesia.io', 'partnerstack', 'aitools'),
    affiliateProgramUrl: 'https://www.synthesia.io/affiliates',
    affiliateProgram: 'partnerstack',
    commissionRate: '20-25% recurring',
    cookieDuration: 90,
    ndnServiceTieIn:
      'NDN Analytics embeds AI video generation into enterprise training and marketing workflows — reducing video production costs by 80%.',
    category: 'design',
    tags: ['ai', 'video', 'avatars', 'training', 'marketing'],
    pricing: 'paid',
    featured: true,
    sortOrder: 30,
    badge: '25% Recurring',
    clickCount: 0,
    isActive: true,
  },
  {
    id: 'descript',
    name: 'Descript',
    tagline: 'All-in-one video and podcast editing',
    description:
      'Edit video and audio by editing the transcript — the most intuitive editor ever made. AI Overdub, filler-word removal, screen recording, and automatic captions built in.',
    logoUrl: 'https://www.descript.com/favicon.ico',
    websiteUrl: 'https://www.descript.com',
    affiliateUrl: buildAffiliateUrl('https://www.descript.com', 'impact', 'aitools'),
    affiliateProgramUrl: 'https://www.descript.com/affiliates',
    affiliateProgram: 'impact',
    commissionRate: '15% recurring',
    cookieDuration: 30,
    ndnServiceTieIn:
      'NDN Interpreter uses similar real-time AI for sign language translation — reducing communication barriers across enterprise.',
    category: 'design',
    tags: ['ai', 'video', 'audio', 'podcasting', 'transcription'],
    pricing: 'freemium',
    featured: false,
    sortOrder: 31,
    clickCount: 0,
    isActive: true,
  },

  // ─── Analytics ────────────────────────────────────────────────────────────
  {
    id: 'surferseo',
    name: 'Surfer SEO',
    tagline: 'AI-powered SEO and content optimization',
    description:
      'Write content that ranks on page one. Real-time NLP-based SEO suggestions, keyword research, content auditing, and SERP analyzer built for content teams and agencies.',
    logoUrl: 'https://surferseo.com/favicon.ico',
    websiteUrl: 'https://surferseo.com',
    affiliateUrl: buildAffiliateUrl('https://surferseo.com', 'surferseo', 'aitools'),
    affiliateProgramUrl: 'https://surferseo.com/affiliate-program',
    affiliateProgram: 'direct',
    commissionRate: '25% recurring',
    cookieDuration: 60,
    ndnServiceTieIn:
      'NDN Analytics implements Surfer SEO alongside our blog auto-generation pipeline to produce content that ranks automatically.',
    category: 'analytics',
    tags: ['seo', 'content', 'ai', 'optimization', 'ranking'],
    pricing: 'paid',
    featured: true,
    sortOrder: 40,
    badge: '25% Recurring',
    clickCount: 0,
    isActive: true,
  },
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    tagline: 'Product analytics that helps you convert, engage, and retain',
    description:
      'Mixpanel is the leading product analytics platform for tracking user behaviour, running A/B tests, and understanding which features drive retention and revenue — with AI-powered insights.',
    logoUrl: 'https://mixpanel.com/favicon.ico',
    websiteUrl: 'https://mixpanel.com',
    affiliateUrl: buildAffiliateUrl('https://mixpanel.com', 'impact', 'aitools'),
    affiliateProgram: 'impact',
    commissionRate: 'Referral credits',
    cookieDuration: 30,
    ndnServiceTieIn:
      'NDN Analytics implements Mixpanel event tracking architectures and builds custom reporting pipelines on your data.',
    category: 'analytics',
    tags: ['product-analytics', 'user-tracking', 'retention', 'a-b-testing'],
    pricing: 'freemium',
    featured: false,
    sortOrder: 41,
    clickCount: 0,
    isActive: true,
  },
  {
    id: 'segment',
    name: 'Segment',
    tagline: 'The leading Customer Data Platform',
    description:
      'Segment collects, unifies, and connects your customer data to 400+ analytics and marketing tools. A single tracking plan eliminates dozens of fragmented integrations.',
    logoUrl: 'https://segment.com/favicon.ico',
    websiteUrl: 'https://segment.com',
    affiliateUrl: buildAffiliateUrl('https://segment.com', 'segment', 'aitools'),
    affiliateProgram: 'direct',
    ndnServiceTieIn:
      'NDN Analytics designs and implements your Segment tracking plan, ensuring clean governed data flows to every downstream tool.',
    category: 'analytics',
    tags: ['cdp', 'data', 'tracking', 'integration', 'marketing-analytics'],
    pricing: 'freemium',
    featured: false,
    sortOrder: 42,
    clickCount: 0,
    isActive: true,
  },

  // ─── Automation ───────────────────────────────────────────────────────────
  {
    id: 'zapier',
    name: 'Zapier',
    tagline: 'Automate your work across 7,000+ apps',
    description:
      'Zapier connects your apps and automates workflows with no code. AI-powered Zaps let you describe the automation you want in plain English and have it built instantly.',
    logoUrl: 'https://cdn.zapier.com/zapier/images/favicon.ico',
    websiteUrl: 'https://zapier.com',
    affiliateUrl: buildAffiliateUrl('https://zapier.com', 'partnerstack', 'aitools'),
    affiliateProgramUrl: 'https://zapier.com/affiliate',
    affiliateProgram: 'partnerstack',
    commissionRate: '20-30%',
    cookieDuration: 90,
    ndnServiceTieIn:
      'NDN Analytics designs multi-step Zapier workflows connecting your CRM, email, Slack, and ERP — eliminating manual data entry.',
    category: 'automation',
    tags: ['no-code', 'integration', 'workflow', 'automation'],
    pricing: 'freemium',
    featured: false,
    sortOrder: 50,
    clickCount: 0,
    isActive: true,
  },
  {
    id: 'make-integromat',
    name: 'Make',
    tagline: 'Visual automation for complex business workflows',
    description:
      'Make (formerly Integromat) is the most powerful visual workflow builder for complex automations requiring data transformation, conditional logic, and multi-branch flows.',
    logoUrl: 'https://www.make.com/favicon.ico',
    websiteUrl: 'https://www.make.com',
    affiliateUrl: buildAffiliateUrl('https://www.make.com/en/register', 'partnerstack', 'aitools'),
    affiliateProgramUrl: 'https://www.make.com/en/partners',
    affiliateProgram: 'partnerstack',
    commissionRate: '20%',
    cookieDuration: 30,
    ndnServiceTieIn:
      'NDN Analytics builds enterprise-grade Make scenarios for supply chain event processing, DeFi alert systems, and healthcare data pipelines.',
    category: 'automation',
    tags: ['no-code', 'integration', 'workflow', 'data-transformation'],
    pricing: 'freemium',
    featured: false,
    sortOrder: 51,
    clickCount: 0,
    isActive: true,
  },

  // ─── Database ─────────────────────────────────────────────────────────────
  {
    id: 'supabase',
    name: 'Supabase',
    tagline: 'The open source Firebase alternative',
    description:
      'Supabase is a fully managed Postgres database with instant REST and GraphQL APIs, real-time subscriptions, auth, storage, and AI vector search built in — free to start.',
    logoUrl: 'https://supabase.com/favicon/favicon-32x32.png',
    websiteUrl: 'https://supabase.com',
    affiliateUrl: buildAffiliateUrl('https://supabase.com', 'supabase', 'aitools'),
    affiliateProgramUrl: 'https://supabase.com/partners/affiliates',
    affiliateProgram: 'supabase',
    commissionRate: '20% first year',
    cookieDuration: 30,
    ndnServiceTieIn:
      'NDN Analytics provisions and optimises Supabase databases for AI applications, including vector search pipelines and row-level security policies.',
    category: 'database',
    tags: ['postgres', 'database', 'vector-search', 'real-time', 'open-source'],
    pricing: 'freemium',
    featured: true,
    sortOrder: 60,
    badge: 'Recommended',
    clickCount: 0,
    isActive: true,
  },

  // ─── Infrastructure ───────────────────────────────────────────────────────
  {
    id: 'vercel',
    name: 'Vercel',
    tagline: 'Deploy web projects with zero configuration',
    description:
      'Vercel is the platform for frontend developers providing the speed and reliability innovators need. AI SDK, v0 generative UI, Edge Network, and seamless GitHub integration built in.',
    logoUrl: 'https://vercel.com/favicon.ico',
    websiteUrl: 'https://vercel.com',
    affiliateUrl: buildAffiliateUrl('https://vercel.com', 'vercel', 'aitools'),
    affiliateProgramUrl: 'https://vercel.com/partners',
    affiliateProgram: 'vercel',
    commissionRate: 'Partner program',
    cookieDuration: 30,
    ndnServiceTieIn:
      'NDN Analytics deploys and optimises React and Next.js applications on Vercel, including Edge Network configuration and ISR caching.',
    category: 'infrastructure',
    tags: ['hosting', 'deployment', 'serverless', 'edge', 'cdn'],
    pricing: 'freemium',
    featured: true,
    sortOrder: 70,
    badge: 'Partner',
    clickCount: 0,
    isActive: true,
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    tagline: 'The global network platform for performance and security',
    description:
      'Cloudflare protects and accelerates any internet application with a global anycast network, DDoS mitigation, WAF, Workers serverless platform, and AI Gateway for LLM rate limiting.',
    logoUrl: 'https://www.cloudflare.com/favicon.ico',
    websiteUrl: 'https://www.cloudflare.com',
    affiliateUrl: buildAffiliateUrl('https://www.cloudflare.com', 'cloudflare', 'aitools'),
    affiliateProgram: 'none',
    ndnServiceTieIn:
      'NDN Analytics configures Cloudflare for enterprise clients — WAF rules, zero-trust access, AI Gateway, and Workers for edge computing.',
    category: 'infrastructure',
    tags: ['cdn', 'security', 'ddos-protection', 'serverless', 'edge'],
    pricing: 'freemium',
    featured: false,
    sortOrder: 71,
    clickCount: 0,
    isActive: true,
  },
];

export default STATIC_PRODUCTS as unknown as AIProduct[];
