import type { Product } from '../../types';

export const PRODUCTS: Product[] = [
  {
    id: 'ndn-001',
    number: 'NDN—001',
    name: 'NDN Demand IQ',
    description: 'AI-powered retail demand forecasting that predicts inventory needs with precision, eliminating stockouts and overstock across complex supply networks.',
    tagline: 'Predict demand before it happens.',
    features: ['Real-time demand sensing', 'Multi-echelon optimization', 'Seasonal pattern recognition', 'Supplier risk modeling'],
    badge: 'Google Cloud',
    stack: 'gcloud',
    icon: '◈',
    industries: ['Retail', 'E-Commerce', 'Consumer Goods', 'Grocery'],
    useCases: [
      'Eliminate costly stockouts during peak seasons with 90-day demand forecasts',
      'Automate purchase orders across thousands of SKUs with AI-driven replenishment',
      'Detect supplier disruption risk weeks before it impacts your shelves',
      'Optimize markdown timing to clear slow-moving inventory at maximum margin',
    ],
    howItWorks: 'NDN Demand IQ ingests your historical sales, external signals (weather, events, economic indicators), and supplier lead times into a Google Cloud Vertex AI pipeline. The model retrains weekly and pushes optimized order recommendations directly to your ERP or WMS.',
    metrics: ['Up to 35% reduction in stockouts', 'Up to 28% reduction in excess inventory', '90-day forecast horizon', 'ERP/WMS native integration'],
  },
  {
    id: 'ndn-002',
    number: 'NDN—002',
    name: 'NDN Care Predict',
    description: 'Hospital readmission prevention AI that identifies at-risk patients before discharge, enabling proactive intervention and reducing costly readmissions.',
    tagline: 'Intervene before readmission happens.',
    features: ['Readmission risk scoring', 'EHR integration', 'Clinical workflow automation', 'Outcome prediction models'],
    badge: 'Healthcare AI',
    stack: 'gcloud',
    icon: '⬡',
    industries: ['Hospital Systems', 'Integrated Health Networks', 'Post-Acute Care', 'Health Insurance'],
    useCases: [
      'Score every discharging patient for 30-day readmission risk in real time',
      'Trigger automated care coordination workflows for high-risk patients',
      'Identify social determinants of health that drive avoidable readmissions',
      'Demonstrate outcomes data to payers for value-based care contracts',
    ],
    howItWorks: 'NDN Care Predict connects to your EHR via HL7/FHIR APIs, pulling clinical notes, lab values, vitals, and social history into a HIPAA-compliant Google Cloud pipeline. The risk model scores patients at each shift change and surfaces actionable alerts inside existing nursing and case management workflows.',
    metrics: ['HIPAA & HITRUST compliant', 'HL7/FHIR native integration', 'Real-time scoring at every shift', 'Integrates with Epic, Cerner, Oracle Health'],
  },
  {
    id: 'ndn-003',
    number: 'NDN—003',
    name: 'NDN Route AI',
    description: 'Last-mile delivery optimization engine that dynamically routes fleets in real time, cutting delivery costs and improving customer satisfaction.',
    tagline: 'Every mile optimized. Every delivery on time.',
    features: ['Dynamic route optimization', 'Fleet telemetry integration', 'Traffic pattern learning', 'Carbon footprint tracking'],
    badge: 'Logistics AI',
    stack: 'gcloud',
    icon: '◉',
    industries: ['Logistics & Courier', '3PL Providers', 'Retail Delivery', 'Food & Grocery Delivery'],
    useCases: [
      'Optimize thousands of stops across hundreds of drivers in under 60 seconds',
      'Dynamically reroute in real time as traffic, weather, or cancellations occur',
      'Reduce carbon emissions with fuel-efficient routing and EV-aware path planning',
      'Give customers accurate ETAs with live driver tracking links',
    ],
    howItWorks: 'NDN Route AI connects to your fleet telematics and order management systems. A Google Cloud optimization engine solves the vehicle routing problem at scale, accounting for time windows, vehicle capacity, driver hours, and real-time traffic. Routes are pushed directly to driver apps.',
    metrics: ['Up to 23% reduction in fuel costs', 'Sub-60s route generation for 1,000+ stops', 'Real-time traffic & weather adaptation', 'EV fleet path planning'],
  },
  {
    id: 'ndn-004',
    number: 'NDN—004',
    name: 'NDN Churn Guard',
    description: 'SaaS churn prevention platform that identifies at-risk accounts weeks in advance and triggers automated retention workflows.',
    tagline: 'Stop churn before your customer even thinks about it.',
    features: ['Behavioral churn signals', 'Health score dashboard', 'Automated intervention flows', 'Revenue impact forecasting'],
    badge: 'SaaS AI',
    stack: 'gcloud',
    icon: '◎',
    industries: ['SaaS Platforms', 'Subscription Services', 'B2B Software', 'Media & Streaming'],
    useCases: [
      'Detect accounts trending toward cancellation 45+ days before renewal',
      'Auto-trigger outreach from CSM teams when health scores drop below threshold',
      'Identify product features most correlated with long-term retention',
      'Quantify at-risk ARR by segment and surface it in executive dashboards',
    ],
    howItWorks: 'NDN Churn Guard pulls product usage events, support ticket sentiment, billing history, and engagement signals into a Google Cloud ML pipeline. The churn propensity model updates daily and pushes risk scores to your CRM (Salesforce, HubSpot) and CSM platform (Gainsight, Totango).',
    metrics: ['45-day early churn warning', 'CRM & CSM native integration', 'ARR-at-risk dashboards', 'Segment-level retention analysis'],
  },
  {
    id: 'ndn-005',
    number: 'NDN—005',
    name: 'NDN TraceChain',
    description: 'Immutable supply chain provenance on Ethereum — track every component from raw material to end consumer with cryptographic certainty.',
    tagline: 'Every product. Every step. On-chain.',
    features: ['On-chain provenance records', 'QR-linked product passports', 'Anti-counterfeiting verification', 'Regulatory audit trails'],
    badge: 'Ethereum',
    stack: 'ethereum',
    icon: '⬡',
    industries: ['Luxury Goods', 'Pharmaceuticals', 'Food & Beverage', 'Electronics Manufacturing'],
    useCases: [
      'Issue a tamper-proof digital product passport at manufacturing, verifiable by any consumer via QR scan',
      'Prove ESG and ethical sourcing claims with cryptographic evidence across your supplier network',
      'Eliminate counterfeit products with on-chain authentication at point of sale',
      'Generate immutable audit trails for FDA, EU supply chain regulation, and customs compliance',
    ],
    howItWorks: 'NDN TraceChain deploys smart contracts on Ethereum mainnet or a private EVM chain. Each supply chain event (manufacture, transfer, inspection, retail) writes a hash to the chain. Consumers and regulators verify provenance via a public API or QR-linked product passport page.',
    metrics: ['Ethereum mainnet & EVM-compatible chains', 'Consumer-facing QR product passports', 'FDA & EU supply chain compliance', 'Real-time counterfeiting alerts'],
  },
  {
    id: 'ndn-006',
    number: 'NDN—006',
    name: 'NDN PayStream',
    description: 'Smart contract payment infrastructure for automated, trustless B2B settlements — milestone-triggered, multi-currency, globally compliant.',
    tagline: 'Payments that execute themselves.',
    features: ['Milestone-based smart payments', 'Multi-currency support', 'Escrow automation', 'Real-time settlement finality'],
    badge: 'Ethereum',
    stack: 'ethereum',
    icon: '◈',
    industries: ['Construction & Real Estate', 'Professional Services', 'International Trade', 'Freelance Platforms'],
    useCases: [
      'Automate contractor milestone payments without manual invoice approval cycles',
      'Hold funds in smart contract escrow until delivery conditions are met on-chain',
      'Settle cross-border B2B payments in seconds with cryptographic finality',
      'Eliminate payment disputes with immutable, pre-agreed contract logic',
    ],
    howItWorks: 'NDN PayStream deploys audited Solidity escrow contracts on Ethereum. Funds lock at contract creation; oracle feeds or authorized signers trigger milestone releases. Multi-signature authorization and time-lock mechanisms protect both parties. Integrates with existing ERP billing flows via API.',
    metrics: ['Multi-sig authorization', 'Oracle-triggered milestone release', 'USDC, ETH, ERC-20 support', 'ERP billing API integration'],
  },
  {
    id: 'ndn-007',
    number: 'NDN—007',
    name: 'NDN CredVault',
    description: 'Decentralized credential verification for workforce and academic credentials — tamper-proof, instantly shareable, employer-verifiable.',
    tagline: 'Trust credentials. Not paperwork.',
    features: ['Blockchain credential issuance', 'Zero-knowledge proof verification', 'Employer API integration', 'Revocation management'],
    badge: 'Ethereum',
    stack: 'ethereum',
    icon: '◉',
    industries: ['Higher Education', 'Professional Certification Bodies', 'Enterprise HR', 'Government'],
    useCases: [
      'Issue university degrees, professional certifications, and training badges as on-chain verifiable credentials',
      'Let candidates share a single verification link instead of paper transcripts',
      'HR teams verify credentials in seconds via API without contacting issuing institutions',
      'Revoke compromised or expired credentials instantly across all downstream verifiers',
    ],
    howItWorks: 'NDN CredVault implements the W3C Verifiable Credentials standard on Ethereum. Issuers sign credentials with their DID (Decentralized Identifier); holders store them in a self-sovereign wallet. Verifiers call our REST API to check authenticity and revocation status without contacting the issuer.',
    metrics: ['W3C Verifiable Credentials standard', 'Decentralized Identifier (DID) based', 'Sub-second verification', 'Instant revocation on-chain'],
  },
  {
    id: 'ndn-008',
    number: 'NDN—008',
    name: 'NDN PropLedger',
    description: 'Real estate tokenization platform enabling fractional property ownership, automated rent distribution, and transparent transaction records on-chain.',
    tagline: 'Real estate ownership, reimagined on-chain.',
    features: ['Property token issuance', 'Fractional ownership management', 'Automated rent distributions', 'On-chain title registry'],
    badge: 'Ethereum',
    stack: 'ethereum',
    icon: '◎',
    industries: ['Real Estate Funds', 'Property Developers', 'REITs', 'Proptech Platforms'],
    useCases: [
      'Tokenize commercial or residential properties into ERC-20 shares for fractional investor access',
      'Distribute rental income to thousands of token holders automatically via smart contract',
      'Record property transfers on-chain for transparent, tamper-proof title history',
      'Enable secondary market trading of property tokens with built-in compliance rules',
    ],
    howItWorks: 'NDN PropLedger issues ERC-20 security tokens representing fractional ownership of legally-structured real estate entities (LLC or SPV). Smart contracts handle income distribution, transfer restrictions (KYC/AML whitelisting), and governance voting. On-chain title records are notarized via Ethereum.',
    metrics: ['ERC-20 security token standard', 'KYC/AML transfer restrictions built-in', 'Automated dividend distribution', 'Secondary market liquidity rails'],
  },
  {
    id: 'ndn-009',
    number: 'NDN—009',
    name: 'Njangi',
    description: 'Community blockchain staking protocol digitizing centuries-old African rotating savings traditions (ROSCAs) for the decentralized era — transparent, trustless, and community-governed.',
    tagline: 'Ancient trust. Decentralized future.',
    features: ['Decentralized savings circles', 'On-chain contribution tracking', 'Smart contract payout rotation', 'Community trust scoring'],
    badge: 'Web3 / Community Finance',
    stack: 'new',
    icon: '★',
    industries: ['Community Finance', 'Diaspora Banking', 'Microfinance', 'Web3 DeFi'],
    useCases: [
      'Form digital savings circles with friends, family, or community members anywhere in the world',
      'Contributions and payout rotations enforced automatically by smart contract — no trusted middleman needed',
      'Build an on-chain reputation score through consistent Njangi participation for future DeFi access',
      'Serve unbanked and underbanked communities with mobile-first, wallet-native savings infrastructure',
    ],
    howItWorks: 'Njangi smart contracts manage circle membership, contribution schedules, and payout rotations. Members deposit funds each cycle; the contract releases the pooled amount to the designated recipient according to the agreed rotation. Trust scores accumulate on-chain and are portable across DeFi protocols.',
    metrics: ['Multi-chain deployment (EVM)', 'Mobile-first wallet interface', 'On-chain trust score system', 'Supports stablecoin contributions'],
  },
  {
    id: 'ndn-010',
    number: 'NDN—010',
    name: 'NeuroQuest',
    description: 'AI-powered cognitive intelligence platform harnessing neural analytics for advanced personality profiling, decision mapping, and behavioral prediction.',
    tagline: 'Understand how minds decide.',
    features: ['Neural pattern analysis', 'Cognitive decision mapping', 'Behavioral prediction models', 'AI personality profiling'],
    badge: 'Cognitive AI',
    stack: 'new',
    icon: '✦',
    industries: ['Talent & HR Tech', 'Executive Coaching', 'Market Research', 'Mental Health Tech'],
    useCases: [
      'Map a candidate\'s cognitive decision style and predict role performance before hiring',
      'Build high-performing teams by understanding cognitive diversity and blind spots',
      'Personalize learning and development programs based on individual neural processing profiles',
      'Deliver deep behavioral insights for market research and consumer psychology studies',
    ],
    howItWorks: 'NeuroQuest administers a validated psychometric assessment battery, then runs results through a neural network trained on cognitive science research. The platform generates a multi-dimensional cognitive profile covering decision style, risk tolerance, creativity index, and interpersonal patterns — delivered via dashboard and API.',
    metrics: ['Validated psychometric battery', 'Multi-dimensional cognitive profiling', 'Team composition analytics', 'API-first for HR platform integration'],
  },
];

export const GCLOUD_PRODUCTS = PRODUCTS.filter(p => p.stack === 'gcloud');
export const ETH_PRODUCTS = PRODUCTS.filter(p => p.stack === 'ethereum');
export const NEW_PRODUCTS = PRODUCTS.filter(p => p.stack === 'new');
