import type { Product } from '../../types';

export const PRODUCTS: Product[] = [
  {
    id: 'ndn-001',
    number: 'NDN—001',
    name: 'NDN Demand IQ',
    description: 'AI-powered retail demand forecasting that predicts inventory needs with precision, eliminating stockouts and overstock across complex supply networks.',
    features: ['Real-time demand sensing', 'Multi-echelon optimization', 'Seasonal pattern recognition', 'Supplier risk modeling'],
    badge: 'Google Cloud',
    stack: 'gcloud',
    icon: '◈',
  },
  {
    id: 'ndn-002',
    number: 'NDN—002',
    name: 'NDN Care Predict',
    description: 'Hospital readmission prevention AI that identifies at-risk patients before discharge, enabling proactive intervention and reducing costly readmissions.',
    features: ['Readmission risk scoring', 'EHR integration', 'Clinical workflow automation', 'Outcome prediction models'],
    badge: 'Healthcare AI',
    stack: 'gcloud',
    icon: '⬡',
  },
  {
    id: 'ndn-003',
    number: 'NDN—003',
    name: 'NDN Route AI',
    description: 'Last-mile delivery optimization engine that dynamically routes fleets in real time, cutting delivery costs and improving customer satisfaction.',
    features: ['Dynamic route optimization', 'Fleet telemetry integration', 'Traffic pattern learning', 'Carbon footprint tracking'],
    badge: 'Logistics AI',
    stack: 'gcloud',
    icon: '◉',
  },
  {
    id: 'ndn-004',
    number: 'NDN—004',
    name: 'NDN Churn Guard',
    description: 'SaaS churn prevention platform that identifies at-risk accounts weeks in advance and triggers automated retention workflows.',
    features: ['Behavioral churn signals', 'Health score dashboard', 'Automated intervention flows', 'Revenue impact forecasting'],
    badge: 'SaaS AI',
    stack: 'gcloud',
    icon: '◎',
  },
  {
    id: 'ndn-005',
    number: 'NDN—005',
    name: 'NDN TraceChain',
    description: 'Immutable supply chain provenance on Ethereum — track every component from raw material to end consumer with cryptographic certainty.',
    features: ['On-chain provenance records', 'QR-linked product passports', 'Anti-counterfeiting verification', 'Regulatory audit trails'],
    badge: 'Ethereum',
    stack: 'ethereum',
    icon: '⬡',
  },
  {
    id: 'ndn-006',
    number: 'NDN—006',
    name: 'NDN PayStream',
    description: 'Smart contract payment infrastructure for automated, trustless B2B settlements — milestone-triggered, multi-currency, globally compliant.',
    features: ['Milestone-based smart payments', 'Multi-currency support', 'Escrow automation', 'Real-time settlement finality'],
    badge: 'Ethereum',
    stack: 'ethereum',
    icon: '◈',
  },
  {
    id: 'ndn-007',
    number: 'NDN—007',
    name: 'NDN CredVault',
    description: 'Decentralized credential verification for workforce and academic credentials — tamper-proof, instantly shareable, employer-verifiable.',
    features: ['Blockchain credential issuance', 'Zero-knowledge proof verification', 'Employer API integration', 'Revocation management'],
    badge: 'Ethereum',
    stack: 'ethereum',
    icon: '◉',
  },
  {
    id: 'ndn-008',
    number: 'NDN—008',
    name: 'NDN PropLedger',
    description: 'Real estate tokenization platform enabling fractional property ownership, automated rent distribution, and transparent transaction records on-chain.',
    features: ['Property token issuance', 'Fractional ownership management', 'Automated rent distributions', 'On-chain title registry'],
    badge: 'Ethereum',
    stack: 'ethereum',
    icon: '◎',
  },
  {
    id: 'ndn-009',
    number: 'NDN—009',
    name: 'Njangi',
    description: 'Community blockchain staking protocol digitizing centuries-old African rotating savings traditions (ROSCAs) for the decentralized era — transparent, trustless, and community-governed.',
    features: ['Decentralized savings circles', 'On-chain contribution tracking', 'Smart contract payout rotation', 'Community trust scoring'],
    badge: 'Web3 / Community Finance',
    stack: 'new',
    icon: '★',
  },
  {
    id: 'ndn-010',
    number: 'NDN—010',
    name: 'NeuroQuest',
    description: 'AI-powered cognitive intelligence platform harnessing neural analytics for advanced personality profiling, decision mapping, and behavioral prediction.',
    features: ['Neural pattern analysis', 'Cognitive decision mapping', 'Behavioral prediction models', 'AI personality profiling'],
    badge: 'Cognitive AI',
    stack: 'new',
    icon: '✦',
  },
];

export const GCLOUD_PRODUCTS = PRODUCTS.filter(p => p.stack === 'gcloud');
export const ETH_PRODUCTS = PRODUCTS.filter(p => p.stack === 'ethereum');
export const NEW_PRODUCTS = PRODUCTS.filter(p => p.stack === 'new');
